version: '3.2'

services:
  db:
    build: .
    image: mcmoe/mssqldocker:v2017.CU24.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: Kobeissi
      MSSQL_PASSWORD: 7ellowEl7akey
    ports:
      - "1433:1433"
    container_name: mssqldev
